ppedv.Personenverwaltung/ppedv.Personenverwaltung.UI.Web.MVC/Models/ErrorViewModel.cs
namespace ppedv.Personenverwaltung.UI.Web.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ppedv.Personenverwaltung/ppedv.Personenverwaltung.UI.Web.MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ppedv.Personenverwaltung.UI.Web.MVC.Models;
using System.Diagnostics;

namespace ppedv.Personenverwaltung.UI.Web.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var zahlen = new int[] { 12, 33, 656, 78345534 };
            return View(zahlen);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ppedv.Personenverwaltung/ppedv.Personenverwaltung.UI.Web.MVC/Controllers/KundenAPIController.cs
using Microsoft.AspNetCore.Mvc;
using ppedv.Personenverwaltung.Logik;
using ppedv.Personenverwaltung.Model;
using ppedv.Personenverwaltung.Model.Contacts;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ppedv.Personenverwaltung.UI.Web.MVC.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class KundenAPIController : ControllerBase
    {
        Core core;

        public KundenAPIController(IRepository repo)
        {
            core = new Core(repo);
        }

        // GET: api/<KundenAPI>
        [HttpGet]
        public IEnumerable<Kunde> Get()
        {
            return core.Repository.GetAll<Kunde>();
        }

        // GET api/<KundenAPI>/5
        [HttpGet("{id}")]
        public Kunde Get(int id)
        {
            return core.Repository.GetById<Kunde>(id);
        }

        // POST api/<KundenAPI>
        [HttpPost]
        public void Post([FromBody] Kunde value)
        {
            core.Repository.Add(value);
            core.Repository.Save();
        }

        // PUT api/<KundenAPI>/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] Kunde value)
        {
            //var loaded = Get(id);
            core.Repository.Update(value);
            core.Repository.Save();
        }

        // DELETE api/<KundenAPI>/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
            var loaded = Get(id);
            core.Repository.Delete(loaded);
            core.Repository.Save();
        }
    }
}

ppedv.Personenverwaltung/ppedv.Personenverwaltung.UI.Web.MVC/Controllers/MitarbeiterController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ppedv.Personenverwaltung.Logik;
using ppedv.Personenverwaltung.Model;
using ppedv.Personenverwaltung.Model.Contacts;

namespace ppedv.Personenverwaltung.UI.Web.MVC.Controllers
{
    public class MitarbeiterController : Controller
    {
        Core core;

        public MitarbeiterController(IRepository repo)
        {
            core = new Core(repo);
        }

        // GET: MitarbeiterController
        public ActionResult Index()
        {
            return View(core.Repository.GetAll<Mitarbeiter>());
        }

        // GET: MitarbeiterController/Details/5
        public ActionResult Details(int id)
        {
            return View(core.Repository.GetById<Mitarbeiter>(id));
        }

        // GET: MitarbeiterController/Create
        public ActionResult Create()
        {
            return View(new Mitarbeiter() { Name = "NEU" });
        }

        // POST: MitarbeiterController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Mitarbeiter mitarbeiter)
        {
            try
            {
                core.Repository.Add(mitarbeiter);
                core.Repository.Save();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MitarbeiterController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(core.Repository.GetById<Mitarbeiter>(id));
        }

        // POST: MitarbeiterController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Mitarbeiter mitarbeiter)
        {
            try
            {
                core.Repository.Update(mitarbeiter);
                core.Repository.Save();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MitarbeiterController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(core.Repository.GetById<Mitarbeiter>(id));
        }

        // POST: MitarbeiterController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                var loaded = core.Repository.GetById<Mitarbeiter>(id);
                core.Repository.Delete(loaded);
                core.Repository.Save();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ppedv.Personenverwaltung/ppedv.Personenverwaltung.UI.Web.MVC/Views/Home/Index.cshtml
@model int[]
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

    <hr />
    @DateTime.Now
    <br/>
    @string.Join(", ", @Model)


</div>

ppedv.Personenverwaltung/ppedv.Personenverwaltung.UI.Web.MVC/Views/Mitarbeiter/Create.cshtml
@using ppedv.Personenverwaltung.Model
@model Mitarbeiter

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Mitarbeiter</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Beruf" class="control-label"></label>
                <input asp-for="Beruf" class="form-control" />
                <span asp-validation-for="Beruf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GebDatum" class="control-label"></label>
                <input asp-for="GebDatum" class="form-control" />
                <span asp-validation-for="GebDatum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ppedv.Personenverwaltung/ppedv.Personenverwaltung.UI.Web.MVC/Views/Mitarbeiter/Delete.cshtml
@using ppedv.Personenverwaltung.Model
@model Mitarbeiter

@{
    ViewData["Title"] = "Delete";
}

<h1>View</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Mitarbeiter</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Beruf)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Beruf)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GebDatum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GebDatum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modified)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modified)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ppedv.Personenverwaltung/ppedv.Personenverwaltung.UI.Web.MVC/Views/Mitarbeiter/Details.cshtml
@using ppedv.Personenverwaltung.Model
@model Mitarbeiter

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Mitarbeiter</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Beruf)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Beruf)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GebDatum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GebDatum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modified)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modified)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

ppedv.Personenverwaltung/ppedv.Personenverwaltung.UI.Web.MVC/Views/Mitarbeiter/Edit.cshtml
@using ppedv.Personenverwaltung.Model
@model Mitarbeiter

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Mitarbeiter</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Beruf" class="control-label"></label>
                <input asp-for="Beruf" class="form-control" />
                <span asp-validation-for="Beruf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GebDatum" class="control-label"></label>
                <input asp-for="GebDatum" class="form-control" />
                <span asp-validation-for="GebDatum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ppedv.Personenverwaltung/ppedv.Personenverwaltung.UI.Web.MVC/Views/Mitarbeiter/Index.cshtml
@model IEnumerable<ppedv.Personenverwaltung.Model.Mitarbeiter>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Beruf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GebDatum)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Created)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modified)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Beruf)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GebDatum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Created)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Modified)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new {  id=item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id=item.Id}) |
                    @Html.ActionLink("Delete", "Delete", new {  id=item.Id})
                </td>
            </tr>
        }
    </tbody>
</table>

ppedv.Personenverwaltung/ppedv.Personenverwaltung.UI.Web.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ppedv.Personenverwaltung.UI.Web.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ppedv.Personenverwaltung.UI.Web.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ppedv.Personenverwaltung.UI.Web.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mitarbeiter" asp-action="Index">Mitarbeiterverwaltung</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ppedv.Personenverwaltung.UI.Web.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>